## Basic Configuration
baseurl = "https://haim-ari.github.io/"
languageCode = "en"
# pygmentsUseClasses=true 
# PygmentsStyle = "monokai"
publishdir = "haim-ari.github.io"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Site Settings


[params]
    author = "Haim Ari"
    title = "Haim Ari"
    description = "Haim Ari"
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "atom-one-dark"
    highlightjsTheme = "Dracula"

    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id"
    # customJS = ["https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"]


## Social Accounts
[params.social]
    github = "haim-ari"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "haimari"
    twitter = "arihaim"
    #facebook = "<username>"
    #stackoverflow = "<username>"
    email = "haimari1@gmail.com"

## Main Menu
[[menu.main]]
    name = "All Posts"
    weight = 600
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "DevOps"
    weight = 200
    identifier = "devops"
    url = "/categories/devops/"
[[menu.main]]
    name = "Scripts"
    weight = 300
    identifier = "scripts"
    url = "/categories/scripts/"
[[menu.main]]
    name = "Docker"
    weight = 400
    identifier = "docker"
    url = "/categories/docker/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/about/"

[taxonomies]
   tag = "tags"
   category = "categories"



